// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUZWmbsQzLTn6E2LsCksCX6BL92xrOuf8',
    appId: '1:35197174649:web:fab690ff26994a8a5865a8',
    messagingSenderId: '35197174649',
    projectId: 'advancebooking-3a827',
    authDomain: 'advancebooking-3a827.firebaseapp.com',
    storageBucket: 'advancebooking-3a827.appspot.com',
    measurementId: 'G-S164W7M2XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1da08UpdiSvGSPl1o9txyPgmBWTba8Ho',
    appId: '1:35197174649:android:a5d137402cb344255865a8',
    messagingSenderId: '35197174649',
    projectId: 'advancebooking-3a827',
    storageBucket: 'advancebooking-3a827.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmwIVQeY_2WgWWuFjhBrI_WbHskl6KLwY',
    appId: '1:35197174649:ios:3c41246907dc19e15865a8',
    messagingSenderId: '35197174649',
    projectId: 'advancebooking-3a827',
    storageBucket: 'advancebooking-3a827.appspot.com',
    iosBundleId: 'com.example.scheduleBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmwIVQeY_2WgWWuFjhBrI_WbHskl6KLwY',
    appId: '1:35197174649:ios:ef78e00e95eff24b5865a8',
    messagingSenderId: '35197174649',
    projectId: 'advancebooking-3a827',
    storageBucket: 'advancebooking-3a827.appspot.com',
    iosBundleId: 'com.example.scheduleBooking.RunnerTests',
  );
}
